### ISSUE TITLE
Errors when comparing an empty slice

### ISSUE THREAD

**Issue by PascalTemel** [adam-hanna/arrayOperations#3]
Taking the quickstart example and modifying it so one slice is empty:

```
var a = []int{1, 1, 2, 3}
var b = []int{}

z, ok := Difference(a, b)
if !ok {
	fmt.Println("Cannot find difference")
}
```

results in an error `reflect: slice index out of range`. I have only tested this with Difference, but I assume it might be the same for the other methods.

**Comment by adam-hanna** [comment]
Excellent, I'm on it.
